### ISSUE TITLE
if is feasible to run your code without nvidia- docker2

### ISSUE THREAD

**Issue by 77hub** [Jacob-yen/LEMON#8]
Dear author,
     Hi, I was amazed when I saw this article of yours. It's the first time I've seen someone come up with such an excellent algorithm for Deep Learning Library Testing, but unfortunately as a beginner I don't really know if is feasible to run your code without nvidia- docker2, so I want to ask you some question. I would be very grateful if you could share the code of your currently published paper "Deep Learning Library Testing via Effective Model Generation.
     I wish you a successful career, a happy family and a happy life.

**Comment by Jacob-yen** [comment]
Thanks for your interest in our paper. 

> I would be very grateful if you could share the code of your currently published paper "Deep Learning Library Testing via Effective Model Generation.

This repository presents the entire implementation of our paper.

>  I don't really know if is feasible to run your code without nvidia- docker2

We have released the docker image(run with GPU and CUDA) used in our experiments on dockerhub for better reproducibility. If you want to run LEMON on machines without GPU and CUDA, you can create the virtual environments(described in Step3) with the python package in the CPU version. For example, change `pip install tensorflow-gpu==1.14.0` to `pip install tensorflow==1.14.0`

Please let me know if you have any further questions.  : )

**Comment by 77hub** [comment]
Hello, I still have some problems. I don't know why this happens. Specifically, as ordinary users of our laboratory server, we can't install NVIDIA docker2 environment, so I want to install tensorflow theano cntk mxnet lemon and other deep learning libraries directly on anaconda3, but when I run in lemon environment according to the code you give, there are large and small errors, such as

1. ImportError: libmpi_ cxx. so. 1: cannot open shared object file: No such file or directory, pygpu. gpuarray.

2. GpuArrayException: b'Could not load "libnvrtc.so": libnvrtc. so: cannot open shared object file: No such file or directory'.

3.OSError: libcudart. so. 10.1: cannot open shared object file: No such file or directory。

4.ModuleNotFoundError: No module named 'cntk._ cntk_ py'.

Wait a minute. I don't know if it's a version update problem. I can't solve this problem. I would appreciate it if you could help me.
